"use client";

import { BankProvider, useBanks } from "@/context/BankContext";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { formatCurrency } from "@/lib/utils";
import Link from "next/link";
import {
  ChevronLeft, Calculator, Download, CreditCard,
  AlertTriangle, CheckCircle2, TrendingUp,
} from "lucide-react";

function TaxContent() {
  const { banks, totalBalance, TAX_RATE } = useBanks();

  const totalTax = totalBalance * TAX_RATE;

  function handlePayTax() {
    alert(`Tax payment of ${formatCurrency(totalTax)} initiated.\n\nThis is a demo — no actual payment processed.`);
  }

  function handleDownload() {
    const lines = [
      "BANKFLOW — TAX SUMMARY REPORT",
      "================================",
      `Report Date : ${new Date().toLocaleDateString("en-BD")}`,
      `Tax Rate    : ${(TAX_RATE * 100).toFixed(0)}% per bank`,
      "",
      "BANK-WISE BREAKDOWN",
      "-------------------",
      ...banks.map(
        (b, i) =>
          `${i + 1}. ${b.bankName.padEnd(30)} Balance: ৳${b.balance.toLocaleString().padStart(12)} | Tax: ৳${(b.balance * TAX_RATE).toLocaleString().padStart(10)}`
      ),
      "",
      "-------------------",
      `TOTAL BALANCE : ৳${totalBalance.toLocaleString()}`,
      `TOTAL TAX     : ৳${totalTax.toLocaleString()}`,
      "",
      "Generated by BankFlow — Demo purposes only",
    ];

    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = "bankflow-tax-report.txt";
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="max-w-2xl mx-auto page-enter">
      {/* Back */}
      <Link
        href="/"
        className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-indigo-600 mb-6 transition-colors font-medium"
      >
        <ChevronLeft size={16} /> Back to Dashboard
      </Link>

      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <div className="w-12 h-12 rounded-2xl gradient-primary flex items-center justify-center shadow-md">
          <Calculator size={22} className="text-white" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-slate-800" style={{ fontFamily: "'Plus Jakarta Sans',sans-serif" }}>
            Tax Calculation
          </h1>
          <p className="text-sm text-slate-400">5% applicable on all linked bank balances</p>
        </div>
      </div>

      {/* Info note */}
      <div className="flex items-start gap-3 bg-amber-50 border border-amber-200 rounded-xl p-3.5 mb-6">
        <AlertTriangle size={16} className="text-amber-500 shrink-0 mt-0.5" />
        <p className="text-xs text-amber-700 leading-relaxed">
          Tax is calculated at a flat rate of <strong>5%</strong> on the current balance of each linked bank account. This is a simplified demo model.
        </p>
      </div>

      {/* Bank-wise breakdown */}
      <div className="bg-white rounded-2xl shadow-card border border-slate-100 overflow-hidden mb-5">
        <div className="px-5 py-4 border-b border-slate-100 bg-slate-50 flex items-center gap-2">
          <CreditCard size={15} className="text-slate-500" />
          <h2 className="text-sm font-bold text-slate-700" style={{ fontFamily: "'Plus Jakarta Sans',sans-serif" }}>
            Bank-wise Tax Breakdown
          </h2>
        </div>

        <div className="divide-y divide-slate-50">
          {banks.map((bank, i) => {
            const tax     = bank.balance * TAX_RATE;
            const percent = totalTax > 0 ? (tax / totalTax) * 100 : 0;
            return (
              <div key={bank.id} className="px-5 py-4">
                <div className="flex items-start justify-between mb-2">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="w-5 h-5 rounded-full gradient-primary text-white text-[10px] font-bold flex items-center justify-center shrink-0">
                        {i + 1}
                      </span>
                      <p className="text-sm font-semibold text-slate-800">{bank.bankName}</p>
                    </div>
                    <p className="text-xs text-slate-400 mt-0.5 ml-7">
                      Balance: <span className="number-display font-medium text-slate-600">{formatCurrency(bank.balance)}</span>
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="number-display text-sm font-bold text-rose-500">
                      {formatCurrency(tax)}
                    </p>
                    <p className="text-xs text-slate-400">@ 5%</p>
                  </div>
                </div>
                {/* Progress bar */}
                <div className="ml-7 h-1.5 bg-slate-100 rounded-full overflow-hidden">
                  <div
                    className="h-full gradient-primary rounded-full transition-all duration-700"
                    style={{ width: `${percent}%` }}
                  />
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Total tax summary card */}
      <div className="gradient-card rounded-2xl p-6 mb-6 text-white relative overflow-hidden">
        {/* Decorative */}
        <div className="absolute -top-10 -right-10 w-40 h-40 rounded-full bg-white opacity-5" />
        <div className="absolute -bottom-8 -left-8 w-32 h-32 rounded-full bg-white opacity-5" />

        <div className="relative z-10">
          <div className="flex items-center gap-2 mb-4">
            <TrendingUp size={16} className="text-indigo-300" />
            <span className="text-xs uppercase tracking-widest text-white/50 font-medium">Tax Summary</span>
          </div>

          <div className="grid grid-cols-3 gap-4">
            <SummaryItem label="Total Balance" value={formatCurrency(totalBalance)} />
            <SummaryItem label="Tax Rate" value="5.00%" accent />
            <SummaryItem label="Total Tax Due" value={formatCurrency(totalTax)} highlight />
          </div>

          <div className="mt-5 pt-4 border-t border-white/10 flex items-center gap-2 text-xs text-white/50">
            <CheckCircle2 size={13} className="text-emerald-400" />
            Calculation based on {banks.length} linked bank account{banks.length !== 1 ? "s" : ""}
          </div>
        </div>
      </div>

      {/* Action buttons */}
      <div className="grid grid-cols-2 gap-3">
        <button
          onClick={handlePayTax}
          className="gradient-primary text-white font-semibold py-3.5 rounded-xl
            hover:opacity-90 active:scale-[0.98] transition-all shadow-md hover:shadow-glow
            flex items-center justify-center gap-2 text-sm"
          style={{ fontFamily: "'Plus Jakarta Sans',sans-serif" }}
        >
          <CreditCard size={16} />
          Pay Tax
        </button>

        <button
          onClick={handleDownload}
          className="bg-white border-2 border-slate-200 text-slate-700 font-semibold py-3.5 rounded-xl
            hover:border-indigo-400 hover:text-indigo-600 active:scale-[0.98] transition-all
            flex items-center justify-center gap-2 text-sm shadow-sm"
          style={{ fontFamily: "'Plus Jakarta Sans',sans-serif" }}
        >
          <Download size={16} />
          Download Tax Paper
        </button>
      </div>
    </div>
  );
}

function SummaryItem({ label, value, accent, highlight }) {
  return (
    <div>
      <p className="text-[10px] uppercase tracking-widest text-white/40 mb-1">{label}</p>
      <p className={`number-display font-bold ${
        highlight ? "text-2xl text-emerald-400" :
        accent    ? "text-xl text-indigo-300" :
                    "text-lg text-white"
      }`}>
        {value}
      </p>
    </div>
  );
}

export default function TaxPage() {
  return (
    <BankProvider>
      <div className="flex flex-col min-h-screen bg-surface-50">
        <Navbar />
        <main className="flex-1 max-w-7xl mx-auto w-full px-4 sm:px-6 lg:px-8 py-8">
          <TaxContent />
        </main>
        <Footer />
      </div>
    </BankProvider>
  );
}
